python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
python -m experiments.matching_nets --dataset SETA --k-test 5 --n-test 10
